image: tboby/docker-fsharp-mono-netcore-electronnet

variables:
  DOCKER_DRIVER: overlay2
  GIT_DEPTH: "3"

stages:
  - build
      
build:
    stage: build
    script:
    - cd ..
    - git clone https://www.github.com/tboby/cwtools
    - cd cwtools-vscode
    - chmod +x ./build.sh
    - bash ./build.sh
   
