image: tboby/docker-fsharp-mono-netcore-electronnet

variables:
  DOCKER_DRIVER: overlay2
  GIT_DEPTH: "3"

stages:
  - build
      
build:
    stage: build
    script:
    - cd ..
    - git clone https://www.github.com/tboby/cwtools
    - cd cwtools-vscode
    - git clone --verbose --mirror "../cwtools" "/root/.paket/git/db/cwtools"
    - cd /root/.paket/git/db/cwtools
    - git remote set-url origin "../cwtools"
    - git remote update --prune
    - cd $CI_PROJECT_DIR
    - mono ./.paket/paket.exe restore --verbose
    - chmod +x ./build.sh
    - bash ./build.sh
    cache:
      paths:
      - packages/
